---
AllCops:
  DisplayCopNames:    true
  DisplayStyleGuide:  true
  StyleGuideCopsOnly: true
  TargetRubyVersion:  2.6
  Exclude:
    - spec/dummy/db/schema.rb
    - vendor/bundle/**/*
    - gemfiles/vendor/**/*
Metrics/ParameterLists:
  Max: 5

Style/Alias:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/FileName:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
