---
sudo:     false
language: ruby
cache:    bundler
script:
  - bundle exec rake
rvm:
  - 2.3.0
  - ruby-head
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
before_install: gem install bundler
matrix:
  allow_failures:
    - rvm: ruby-head
